# infos

With this notebook, we can label the datasets, we train a model that proposes the correct class, and we either confirm or asign the correct class

In [1]:
import sys, os


import logging
import pandas as pd
import numpy as np
from pathlib import Path
# sys.path.insert(0,'..')
project_dir = str(Path(os.getcwd()).parent)
if not project_dir in sys.path:
    sys.path.insert(0,project_dir)
sys.path
from BankClassify import BankClassify

In [2]:

%load_ext autoreload

%autoreload 2

Debug levels:
|Level | Numeric value|
|---|---|
|CRITICAL | 50|
|ERROR | 40|
|WARNING| 30|
|INFO| 20|
|DEBUG| 10|
|NOTSET| 0|

In [3]:
logging.basicConfig(level=logging.INFO)

# Label data

### load data and create classifier

In [4]:
bc = BankClassify(Path('../data'))

INFO:root:loaded previous dkb_3109 data 541 entries
INFO:root:loaded previous dkb_4217 data 1212 entries
INFO:root:train dataset size 1267

In [5]:
data_unlabeled = bc.data_unlabeled
print(f"{len(data_unlabeled)} unlabeled entries")
predictions = bc._make_predictions(data_unlabeled)

57 unlabeled entries

In [6]:
# predictions.columns = ['class_guess', 'class_prob']
# predictions

### make guess

##### order by class probability

In [7]:
data_unlabeled_with_guess = pd.concat([data_unlabeled, predictions], ignore_index=False, axis=1, copy=False, join='inner')
data_unlabeled_with_guess.sort_values('class_prob', inplace=True) # sort such that the ones with the highest uncertainty come first
data_unlabeled_with_guess

                   date    amount  \
dkb_3109 490 2022-09-19    -42.80
         504 2022-09-06    -22.59
         498 2022-09-09     -5.69
         506 2022-09-06     -4.90
         505 2022-09-06    -12.60
         496 2022-09-12    -26.00
         500 2022-09-08     -1.44
         539 2022-08-08   -116.01
         501 2022-09-07    -65.95
         499 2022-09-08     -3.95
         514 2022-08-30    -39.00
         518 2022-08-29     -7.00
         477 2022-09-30   -315.64
         478 2022-09-30     -4.00
         515 2022-08-30     -9.30
         522 2022-08-24    -38.00
         491 2022-09-19    -18.59
         495 2022-09-12    -34.00
         511 2022-09-01    -48.00
         485 2022-09-22    -48.00
         497 2022-09-09    -48.00
         529 2022-08-22    -48.00
         481 2022-09-27    -69.00
         510 2022-09-01    -48.00
         535 2022-08-15    -48.00
         489 2022-09-19    -48.00
         531 2022-08-19    150.00
         492 2022-09-19    -11.94
         540 2022-08-08    -61.00
         503 2022-09-06    -61.00
         523 2022-08-24     -3.80
         533 2022-08-16    -17.80
         493 2022-09-19     -5.00
         536 2022-08-15    -29.05
         487 2022-09-21  -1000.00
         486 2022-09-21  -1000.00
         526 2022-08-22  -1000.00
         525 2022-08-22  -1000.00
         483 2022-09-26    -29.84
         534 2022-08-15    -55.08
         532 2022-08-18     -2.44
         509 2022-09-01  -2450.50
         528 2022-08-22    -56.58
         480 2022-09-28   4157.32
         516 2022-08-30   3983.32
         484 2022-09-26    -19.99
         520 2022-08-25    -19.99
         527 2022-08-22    -90.00
         488 2022-09-20    -90.00
         513 2022-08-30 -20000.00
         512 2022-08-31 -20000.00
         519 2022-08-26 -25000.00
         508 2022-09-05    -23.00
         479 2022-09-29    -39.99
         517 2022-08-29    -39.99
         507 2022-09-05   -100.00
         502 2022-09-06   -100.00

                                                           desc  account_nr  \
dkb_3109 490  Kartenzahlung/-abrechnung ALDI SAGT DANKE 28 0...  1002423109
         504  Kartenzahlung/-abrechnung Kiez Markt GIR 69038...  1002423109
         498  Kartenzahlung/-abrechnung Burger King 15800//N...  1002423109
         506  Kartenzahlung/-abrechnung DENN?S BIOMARKT BER/...  1002423109
         505  Kartenzahlung/-abrechnung DENN?S BIOMARKT BER/...  1002423109
         496  Kartenzahlung/-abrechnung BEZIRKSAMT CHARLOTTE...  1002423109
         500  Kartenzahlung/-abrechnung MUELLER SAGT DANKE//...  1002423109
         539  Kartenzahlung/-abrechnung AMBROSINO SUPERMARKT...  1002423109
         501  Kartenzahlung/-abrechnung DECATHLON Deutschlan...  1002423109
         499  Kartenzahlung/-abrechnung Der Beck GmbH Filial...  1002423109
         514  Kartenzahlung/-abrechnung MARIA BONITA//BERLIN...  1002423109
         518  Kartenzahlung/-abrechnung BRLO Gastro. Holding...  1002423109
         477  Kartenzahlung/-abrechnung VIVA RESORT PROT.PRI...  1002423109
         478  Kartenzahlung/-abrechnung H.RESORT SUPERMERCAD...  1002423109
         515  Kartenzahlung/-abrechnung IZ .GIMME GELATO G//...  1002423109
         522  Kartenzahlung/-abrechnung Photo Zentrum//Berli...  1002423109
         491  Kartenzahlung/-abrechnung ASIL GMBH//BERLIN/DE...  1002423109
         495  Kartenzahlung/-abrechnung VINOTRIA GMBH CO KG/...  1002423109
         511  Überweisung GISELA SILVA Rechnungs-Nr.: 116/20...  1002423109
         485  Überweisung GISELA SILVA Rechnungs-Nr.: 138/20...  1002423109
         497  Überweisung GISELA SILVA Rechnungs-Nr.: 129/20...  1002423109
         529  Überweisung GISELA SILVA Rechnungs-Nr.: 111/20...  1002423109
         481  Überweisung GISELA SILVA Rechnungs-Nr.: 142/20...  1002423109
         510  Überweisung GISELA SILVA Rechnungs-Nr.: 120/20...  1002423109
         535  Überweisung GISELA SILVA Rechnungs-Nr.: 100/20...  1002423109
         489  Überweisung GISELA SILVA Rechnungs-Nr.: 133/20...  1002423109
         531  Gutschrift CORNELIA GIESELER UND DR. S TEFFEN ...  1002423109
         492  Kartenzahlung/-abrechnung Atlantis-Apotheke//B...  1002423109
         540  Lastschrift VATTENFALL EUROPE SALES S/83663436...  1002423109
         503  Lastschrift VATTENFALL EUROPE SALES S/83663436...  1002423109
         523  Kartenzahlung/-abrechnung SumUp .vanille maril...  1002423109
         533  Kartenzahlung/-abrechnung BARES GbR//Berlin/DE...  1002423109
         493  Kartenzahlung/-abrechnung BONG APOTHEKE//BERLI...  1002423109
         536  Kartenzahlung/-abrechnung ROSSMANN VIELEN DANK...  1002423109
         487  Lastschrift Sauren SICAV SPARPLAN ISIN LU17170...  1002423109
         486  Lastschrift Sauren SICAV SPARPLAN ISIN LU01155...  1002423109
         526  Lastschrift Sauren SICAV SPARPLAN ISIN LU17170...  1002423109
         525  Lastschrift Sauren SICAV SPARPLAN ISIN LU01155...  1002423109
         483  Kartenzahlung/-abrechnung EDEKA GRACKA, BERLIN...  1002423109
         534  Lastschrift Rundfunk ARD, ZDF, DRadio Rundfunk...  1002423109
         532  Kartenzahlung/-abrechnung DIRK ROSSMANN GMBH//...  1002423109
         509  Lastschrift Aberdeen Standard Investments Deut...  1002423109
         528  Kartenzahlung/-abrechnung SB Tank 7784// Hoyer...  1002423109
         480  Lohn, Gehalt, Rente IAV GmbH Ingenieurgesellsc...  1002423109
         516  Lohn, Gehalt, Rente IAV GmbH Ingenieurgesellsc...  1002423109
         484  Lastschrift Vodafone GmbH 0000114111198 001835...  1002423109
         520  Lastschrift Vodafone GmbH 0000114111198 001829...  1002423109
         527  Dauerauftrag GIRASOLES-FOERDERVEREIN E. V.  I....  1002423109
         488  Dauerauftrag GIRASOLES-FOERDERVEREIN E. V.  I....  1002423109
         513  Lastschrift European Bank for Financial Servic...  1002423109
         512  Lastschrift European Bank for Financial Servic...  1002423109
         519  Lastschrift European Bank for Financial Servic...  1002423109
         508  Lastschrift GIRASOLES - SONNENBLUMEN Beitrag N...  1002423109
         479  Lastschrift Vodafone Deutschland GmbH 09/2022 ...  1002423109
         517  Lastschrift Vodafone Deutschland GmbH 08/2022 ...  1002423109
         507  Lastschrift European Bank for Financial Servic...  1002423109
         502  Lastschrift European Bank for Financial Servic...  1002423109

             target account class                         class_guess  \
dkb_3109 490            NaN   NaN             Holidays - Accomodation
         504            NaN   NaN  Supermarket & Everyday commodities
         498            NaN   NaN             Holidays - Accomodation
         506            NaN   NaN             Holidays - Accomodation
         505            NaN   NaN             Holidays - Accomodation
         496            NaN   NaN                 Presents for Others
         500            NaN   NaN                Income - Investments
         539            NaN   NaN  Supermarket & Everyday commodities
         501            NaN   NaN                Income - Investments
         499            NaN   NaN                 Presents for Others
         514            NaN   NaN                  Restaurants & Bars
         518            NaN   NaN                  Restaurants & Bars
         477            NaN   NaN                  Restaurants & Bars
         478            NaN   NaN                  Restaurants & Bars
         515            NaN   NaN                  Restaurants & Bars
         522            NaN   NaN                  Restaurants & Bars
         491            NaN   NaN                  Restaurants & Bars
         495            NaN   NaN                  Restaurants & Bars
         511            NaN   NaN                           Education
         485            NaN   NaN                           Education
         497            NaN   NaN                           Education
         529            NaN   NaN                           Education
         481            NaN   NaN                           Education
         510            NaN   NaN                           Education
         535            NaN   NaN                           Education
         489            NaN   NaN                           Education
         531            NaN   NaN                   Income - Presents
         492            NaN   NaN               Personal Care & Sport
         540            NaN   NaN       Bill - Utilities, Rent & Fees
         503            NaN   NaN       Bill - Utilities, Rent & Fees
         523            NaN   NaN                  Restaurants & Bars
         533            NaN   NaN                  Restaurants & Bars
         493            NaN   NaN               Personal Care & Sport
         536            NaN   NaN  Supermarket & Everyday commodities
         487            NaN   NaN                         Investments
         486            NaN   NaN                         Investments
         526            NaN   NaN                         Investments
         525            NaN   NaN                         Investments
         483            NaN   NaN  Supermarket & Everyday commodities
         534            NaN   NaN                Income - Investments
         532            NaN   NaN  Supermarket & Everyday commodities
         509            NaN   NaN       Bill - Utilities, Rent & Fees
         528            NaN   NaN                                 Car
         480            NaN   NaN          Income - Salary & Benefits
         516            NaN   NaN          Income - Salary & Benefits
         484            NaN   NaN               Bill - Communications
         520            NaN   NaN               Bill - Communications
         527            NaN   NaN                           Education
         488            NaN   NaN                           Education
         513            NaN   NaN                         Investments
         512            NaN   NaN                         Investments
         519            NaN   NaN                         Investments
         508            NaN   NaN                           Education
         479            NaN   NaN               Bill - Communications
         517            NaN   NaN               Bill - Communications
         507            NaN   NaN                         Investments
         502            NaN   NaN                         Investments

              class_prob
dkb_3109 490    0.278804
         504    0.279199
         498    0.376962
         506    0.420518
         505    0.420518
         496    0.491486
         500    0.514243
         539    0.520064
         501    0.531505
         499    0.570958
         514    0.583140
         518    0.606525
         477    0.670434
         478    0.670434
         515    0.707406
         522    0.707406
         491    0.746091
         495    0.782159
         511    0.807505
         485    0.807505
         497    0.807505
         529    0.807505
         481    0.807505
         510    0.807505
         535    0.807505
         489    0.807505
         531    0.836781
         492    0.850815
         540    0.870812
         503    0.870812
         523    0.891861
         533    0.959206
         493    0.960068
         536    0.968196
         487    0.974513
         486    0.974513
         526    0.974513
         525    0.974513
         483    0.990265
         534    0.994791
         532    0.995979
         509    0.997779
         528    0.999294
         480    0.999337
         516    0.999337
         484    0.999849
         520    0.999849
         527    0.999905
         488    0.999905
         513    0.999936
         512    0.999936
         519    0.999936
         508    0.999963
         479    0.999995
         517    0.999995
         507    1.000000
         502    1.000000

##### order by value

In [8]:
data_unlabeled_with_guess = pd.concat([data_unlabeled, predictions], ignore_index=False, axis=1, copy=False, join='inner')
data_unlabeled_with_guess.sort_values('amount', inplace=True, ascending=False) # sort such that the ones with the highest uncertainty come first
data_unlabeled_with_guess

                   date    amount  \
dkb_3109 480 2022-09-28   4157.32
         516 2022-08-30   3983.32
         531 2022-08-19    150.00
         500 2022-09-08     -1.44
         532 2022-08-18     -2.44
         523 2022-08-24     -3.80
         499 2022-09-08     -3.95
         478 2022-09-30     -4.00
         506 2022-09-06     -4.90
         493 2022-09-19     -5.00
         498 2022-09-09     -5.69
         518 2022-08-29     -7.00
         515 2022-08-30     -9.30
         492 2022-09-19    -11.94
         505 2022-09-06    -12.60
         533 2022-08-16    -17.80
         491 2022-09-19    -18.59
         484 2022-09-26    -19.99
         520 2022-08-25    -19.99
         504 2022-09-06    -22.59
         508 2022-09-05    -23.00
         496 2022-09-12    -26.00
         536 2022-08-15    -29.05
         483 2022-09-26    -29.84
         495 2022-09-12    -34.00
         522 2022-08-24    -38.00
         514 2022-08-30    -39.00
         517 2022-08-29    -39.99
         479 2022-09-29    -39.99
         490 2022-09-19    -42.80
         529 2022-08-22    -48.00
         497 2022-09-09    -48.00
         510 2022-09-01    -48.00
         511 2022-09-01    -48.00
         489 2022-09-19    -48.00
         535 2022-08-15    -48.00
         485 2022-09-22    -48.00
         534 2022-08-15    -55.08
         528 2022-08-22    -56.58
         540 2022-08-08    -61.00
         503 2022-09-06    -61.00
         501 2022-09-07    -65.95
         481 2022-09-27    -69.00
         527 2022-08-22    -90.00
         488 2022-09-20    -90.00
         507 2022-09-05   -100.00
         502 2022-09-06   -100.00
         539 2022-08-08   -116.01
         477 2022-09-30   -315.64
         526 2022-08-22  -1000.00
         525 2022-08-22  -1000.00
         487 2022-09-21  -1000.00
         486 2022-09-21  -1000.00
         509 2022-09-01  -2450.50
         513 2022-08-30 -20000.00
         512 2022-08-31 -20000.00
         519 2022-08-26 -25000.00

                                                           desc  account_nr  \
dkb_3109 480  Lohn, Gehalt, Rente IAV GmbH Ingenieurgesellsc...  1002423109
         516  Lohn, Gehalt, Rente IAV GmbH Ingenieurgesellsc...  1002423109
         531  Gutschrift CORNELIA GIESELER UND DR. S TEFFEN ...  1002423109
         500  Kartenzahlung/-abrechnung MUELLER SAGT DANKE//...  1002423109
         532  Kartenzahlung/-abrechnung DIRK ROSSMANN GMBH//...  1002423109
         523  Kartenzahlung/-abrechnung SumUp .vanille maril...  1002423109
         499  Kartenzahlung/-abrechnung Der Beck GmbH Filial...  1002423109
         478  Kartenzahlung/-abrechnung H.RESORT SUPERMERCAD...  1002423109
         506  Kartenzahlung/-abrechnung DENN?S BIOMARKT BER/...  1002423109
         493  Kartenzahlung/-abrechnung BONG APOTHEKE//BERLI...  1002423109
         498  Kartenzahlung/-abrechnung Burger King 15800//N...  1002423109
         518  Kartenzahlung/-abrechnung BRLO Gastro. Holding...  1002423109
         515  Kartenzahlung/-abrechnung IZ .GIMME GELATO G//...  1002423109
         492  Kartenzahlung/-abrechnung Atlantis-Apotheke//B...  1002423109
         505  Kartenzahlung/-abrechnung DENN?S BIOMARKT BER/...  1002423109
         533  Kartenzahlung/-abrechnung BARES GbR//Berlin/DE...  1002423109
         491  Kartenzahlung/-abrechnung ASIL GMBH//BERLIN/DE...  1002423109
         484  Lastschrift Vodafone GmbH 0000114111198 001835...  1002423109
         520  Lastschrift Vodafone GmbH 0000114111198 001829...  1002423109
         504  Kartenzahlung/-abrechnung Kiez Markt GIR 69038...  1002423109
         508  Lastschrift GIRASOLES - SONNENBLUMEN Beitrag N...  1002423109
         496  Kartenzahlung/-abrechnung BEZIRKSAMT CHARLOTTE...  1002423109
         536  Kartenzahlung/-abrechnung ROSSMANN VIELEN DANK...  1002423109
         483  Kartenzahlung/-abrechnung EDEKA GRACKA, BERLIN...  1002423109
         495  Kartenzahlung/-abrechnung VINOTRIA GMBH CO KG/...  1002423109
         522  Kartenzahlung/-abrechnung Photo Zentrum//Berli...  1002423109
         514  Kartenzahlung/-abrechnung MARIA BONITA//BERLIN...  1002423109
         517  Lastschrift Vodafone Deutschland GmbH 08/2022 ...  1002423109
         479  Lastschrift Vodafone Deutschland GmbH 09/2022 ...  1002423109
         490  Kartenzahlung/-abrechnung ALDI SAGT DANKE 28 0...  1002423109
         529  Überweisung GISELA SILVA Rechnungs-Nr.: 111/20...  1002423109
         497  Überweisung GISELA SILVA Rechnungs-Nr.: 129/20...  1002423109
         510  Überweisung GISELA SILVA Rechnungs-Nr.: 120/20...  1002423109
         511  Überweisung GISELA SILVA Rechnungs-Nr.: 116/20...  1002423109
         489  Überweisung GISELA SILVA Rechnungs-Nr.: 133/20...  1002423109
         535  Überweisung GISELA SILVA Rechnungs-Nr.: 100/20...  1002423109
         485  Überweisung GISELA SILVA Rechnungs-Nr.: 138/20...  1002423109
         534  Lastschrift Rundfunk ARD, ZDF, DRadio Rundfunk...  1002423109
         528  Kartenzahlung/-abrechnung SB Tank 7784// Hoyer...  1002423109
         540  Lastschrift VATTENFALL EUROPE SALES S/83663436...  1002423109
         503  Lastschrift VATTENFALL EUROPE SALES S/83663436...  1002423109
         501  Kartenzahlung/-abrechnung DECATHLON Deutschlan...  1002423109
         481  Überweisung GISELA SILVA Rechnungs-Nr.: 142/20...  1002423109
         527  Dauerauftrag GIRASOLES-FOERDERVEREIN E. V.  I....  1002423109
         488  Dauerauftrag GIRASOLES-FOERDERVEREIN E. V.  I....  1002423109
         507  Lastschrift European Bank for Financial Servic...  1002423109
         502  Lastschrift European Bank for Financial Servic...  1002423109
         539  Kartenzahlung/-abrechnung AMBROSINO SUPERMARKT...  1002423109
         477  Kartenzahlung/-abrechnung VIVA RESORT PROT.PRI...  1002423109
         526  Lastschrift Sauren SICAV SPARPLAN ISIN LU17170...  1002423109
         525  Lastschrift Sauren SICAV SPARPLAN ISIN LU01155...  1002423109
         487  Lastschrift Sauren SICAV SPARPLAN ISIN LU17170...  1002423109
         486  Lastschrift Sauren SICAV SPARPLAN ISIN LU01155...  1002423109
         509  Lastschrift Aberdeen Standard Investments Deut...  1002423109
         513  Lastschrift European Bank for Financial Servic...  1002423109
         512  Lastschrift European Bank for Financial Servic...  1002423109
         519  Lastschrift European Bank for Financial Servic...  1002423109

             target account class                         class_guess  \
dkb_3109 480            NaN   NaN          Income - Salary & Benefits
         516            NaN   NaN          Income - Salary & Benefits
         531            NaN   NaN                   Income - Presents
         500            NaN   NaN                Income - Investments
         532            NaN   NaN  Supermarket & Everyday commodities
         523            NaN   NaN                  Restaurants & Bars
         499            NaN   NaN                 Presents for Others
         478            NaN   NaN                  Restaurants & Bars
         506            NaN   NaN             Holidays - Accomodation
         493            NaN   NaN               Personal Care & Sport
         498            NaN   NaN             Holidays - Accomodation
         518            NaN   NaN                  Restaurants & Bars
         515            NaN   NaN                  Restaurants & Bars
         492            NaN   NaN               Personal Care & Sport
         505            NaN   NaN             Holidays - Accomodation
         533            NaN   NaN                  Restaurants & Bars
         491            NaN   NaN                  Restaurants & Bars
         484            NaN   NaN               Bill - Communications
         520            NaN   NaN               Bill - Communications
         504            NaN   NaN  Supermarket & Everyday commodities
         508            NaN   NaN                           Education
         496            NaN   NaN                 Presents for Others
         536            NaN   NaN  Supermarket & Everyday commodities
         483            NaN   NaN  Supermarket & Everyday commodities
         495            NaN   NaN                  Restaurants & Bars
         522            NaN   NaN                  Restaurants & Bars
         514            NaN   NaN                  Restaurants & Bars
         517            NaN   NaN               Bill - Communications
         479            NaN   NaN               Bill - Communications
         490            NaN   NaN             Holidays - Accomodation
         529            NaN   NaN                           Education
         497            NaN   NaN                           Education
         510            NaN   NaN                           Education
         511            NaN   NaN                           Education
         489            NaN   NaN                           Education
         535            NaN   NaN                           Education
         485            NaN   NaN                           Education
         534            NaN   NaN                Income - Investments
         528            NaN   NaN                                 Car
         540            NaN   NaN       Bill - Utilities, Rent & Fees
         503            NaN   NaN       Bill - Utilities, Rent & Fees
         501            NaN   NaN                Income - Investments
         481            NaN   NaN                           Education
         527            NaN   NaN                           Education
         488            NaN   NaN                           Education
         507            NaN   NaN                         Investments
         502            NaN   NaN                         Investments
         539            NaN   NaN  Supermarket & Everyday commodities
         477            NaN   NaN                  Restaurants & Bars
         526            NaN   NaN                         Investments
         525            NaN   NaN                         Investments
         487            NaN   NaN                         Investments
         486            NaN   NaN                         Investments
         509            NaN   NaN       Bill - Utilities, Rent & Fees
         513            NaN   NaN                         Investments
         512            NaN   NaN                         Investments
         519            NaN   NaN                         Investments

              class_prob
dkb_3109 480    0.999337
         516    0.999337
         531    0.836781
         500    0.514243
         532    0.995979
         523    0.891861
         499    0.570958
         478    0.670434
         506    0.420518
         493    0.960068
         498    0.376962
         518    0.606525
         515    0.707406
         492    0.850815
         505    0.420518
         533    0.959206
         491    0.746091
         484    0.999849
         520    0.999849
         504    0.279199
         508    0.999963
         496    0.491486
         536    0.968196
         483    0.990265
         495    0.782159
         522    0.707406
         514    0.583140
         517    0.999995
         479    0.999995
         490    0.278804
         529    0.807505
         497    0.807505
         510    0.807505
         511    0.807505
         489    0.807505
         535    0.807505
         485    0.807505
         534    0.994791
         528    0.999294
         540    0.870812
         503    0.870812
         501    0.531505
         481    0.807505
         527    0.999905
         488    0.999905
         507    1.000000
         502    1.000000
         539    0.520064
         477    0.670434
         526    0.974513
         525    0.974513
         487    0.974513
         486    0.974513
         509    0.997779
         513    0.999936
         512    0.999936
         519    0.999936

### interactively ask if guess is correct

In [9]:
# bc.prob_threshold = 1

In [10]:
df = bc._ask_with_guess(data_unlabeled_with_guess)

INFO:root:asking with guess, total 62

============================================================
==== to exit interactive mode enter "q" and hit enter ======
============================================================
On: 2022-08-23 00:00:00	 20000.00
Gutschrift Jan Gieseler und Camila Lobo Costa deposit
My guess is: Income - Investments 66.81%

>  q

exiting ...

In [27]:
16# data_unlabeled_with_guess

In [10]:
len(data_unlabeled_with_guess)

295

In [11]:
data_unlabeled_with_guess

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
1201,2022-06-02,-2070.00,"Überweisung DANNY KRAUTZ Buzios, praja, sol, f...",1.002423e+09,NaN,Income - Reimbursement,Bill - Health,0.887936
531,2020-05-29,-700.00,Überweisung ERICO VICENTE CIANCIO armario ...,1.002423e+09,NaN,Home Improvement & Stationary,Bill - Health,0.926238
592,2021-11-29,-595.00,"Überweisung DOMUS AG Rechnr.945, Mandant: 4082...",1.071944e+09,NaN,"Bill - Utilities, Rent & Fees",Bill - Health,0.887936
364,2021-04-06,-530.14,Überweisung NOAK KUBE TISCHLEREI GMBH Schreibt...,1.002423e+09,NaN,Home Improvement & Stationary,Bill - Health,0.948915
1315,2022-08-02,-300.00,Kartenzahlung/-abrechnung Hotel Kranichsberg//...,1.071944e+09,NaN,Holidays - Accomodation,Clothes & Shopping,0.913434
...,...,...,...,...,...,...,...,...
537,2020-05-05,3000.00,Gutschrift CORNELIA GIESELER UND DR. S TEFFEN ...,1.002423e+09,NaN,NaN,Income - Presents,0.993445
559,2020-01-03,4000.00,Gutschrift DR.ST. U. C. GIESELER Weihnachten O...,1.002423e+09,NaN,NaN,Income - Presents,0.996949
334,2021-05-26,4111.75,Gutschrift DR.ST. U. C. GIESELER Betrag Aktien...,1.002423e+09,NaN,NaN,Income - Presents,0.999664
532,2020-05-25,5000.00,Gutschrift DR.ST. U. C. GIESELER Koblenz Oma.O...,1.002423e+09,NaN,NaN,Income - Presents,0.994370
1353,2022-07-15,80000.00,Gutschrift KTO3036000010004294/ JOAO VIRGILIO ...,1.071944e+09,NaN,NaN,Income - Presents,0.998048

In [12]:
len(bc.data['dkb'])

1689

In [13]:
# data_unlabeled_with_guess.loc[311]

In [ ]:
bc.data['dkb'].loc[311]

<a id=’section_update’></a>
### update the dataset

In [204]:
bc.update_data(data_unlabeled_with_guess)

In [205]:
# bc.data['dkb'].update(data_unlabeled_with_guess[data_unlabeled_with_guess.columns[~data_unlabeled_with_guess.columns.isin(['class_guess', 'class_prob'])]])

#### save dataset

In [206]:
bc.save_data()

### manual labeling

after asigning the labels or the target account go to [Section Update](#section_update) to update and save the data to disk.

##### add target account

In [23]:
data_unlabeled_with_guess[data_unlabeled_with_guess['target account'].isna()]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
1602,2022-03-08,-25.30,Kartenzahlung/-abrechnung CAFE IM LITERATURHAU...,1.071944e+09,NaN,NaN,Home Improvement & Stationary,0.311130
656,2021-11-01,-17.00,Kartenzahlung/-abrechnung DORINT GMBH GIR 6929...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.372674
652,2021-11-01,-123.80,Kartenzahlung/-abrechnung DORINT GMBH GIR 6929...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.372674
749,2021-09-13,-10.68,Kartenzahlung/-abrechnung DANKE FLEISCHEREI GL...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.471710
682,2021-10-18,-25.72,Kartenzahlung/-abrechnung DANKE FLEISCHEREI GL...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.471710
...,...,...,...,...,...,...,...,...
1206,2022-05-30,500.00,Gutschrift DR.ST. U. C. GIESELER Alles Gute zu...,1.002423e+09,NaN,NaN,Income - Presents,0.999417
334,2021-05-26,4111.75,Gutschrift DR.ST. U. C. GIESELER Betrag Aktien...,1.002423e+09,NaN,NaN,Income - Presents,0.999656
520,2020-07-01,-2229.12,Lastschrift Aberdeen Asset Management Deutschl...,1.002423e+09,NaN,NaN,"Bill - Utilities, Rent & Fees",0.999687
1171,2022-07-04,-120.00,Überweisung EDITH ESPINOZA DE THIEKE Rechn.Nr....,1.002423e+09,NaN,NaN,"Bill - Utilities, Rent & Fees",0.999821
410,2021-02-02,12.50,Gutschrift DR.ST. U. C. GIESELER Dividende aus...,1.002423e+09,NaN,NaN,Income - Presents,0.999851

In [56]:
bc.data['dkb']['target account'].unique()

array(['paypal', nan, 'Sabadell', 'dkb', 'credit card'], dtype=object)

In [143]:
# data_unlabeled_with_guess

In [55]:
credit_indecies = data_unlabeled_with_guess['desc'].str.lower().str.contains('Gutschrift Jan Gieseler'.lower())
credit_indecies.sum()
data_unlabeled_with_guess[credit_indecies]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
554,2020-02-04,1000.00,Gutschrift JAN GIESELER poupar ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
551,2020-02-19,2500.00,Gutschrift JAN GIESELER poupen ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
547,2020-03-26,2500.00,Gutschrift JAN GIESELER popen ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
341,2021-05-11,12548.11,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
467,2020-10-28,2750.00,Gutschrift JAN GIESELER restbetrag ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
516,2020-07-14,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
437,2020-12-08,2750.00,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
512,2020-07-27,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
539,2020-04-24,2500.00,Gutschrift JAN GIESELER spargeld ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
522,2020-06-26,2500.00,Gutschrift JAN GIESELER poupa ...,1.002423e+09,NaN,NaN,Public Transport,0.885461

In [57]:
data_unlabeled_with_guess.loc[credit_indecies, 'target account'] = 'Sabadell'

In [58]:
data_unlabeled_with_guess[credit_indecies]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
554,2020-02-04,1000.00,Gutschrift JAN GIESELER poupar ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
551,2020-02-19,2500.00,Gutschrift JAN GIESELER poupen ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
547,2020-03-26,2500.00,Gutschrift JAN GIESELER popen ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
341,2021-05-11,12548.11,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
467,2020-10-28,2750.00,Gutschrift JAN GIESELER restbetrag ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
516,2020-07-14,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
437,2020-12-08,2750.00,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
512,2020-07-27,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
539,2020-04-24,2500.00,Gutschrift JAN GIESELER spargeld ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
522,2020-06-26,2500.00,Gutschrift JAN GIESELER poupa ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461

In [46]:
credit_indecies.sum()

7

##### set labels

In [169]:
indecies = data_unlabeled_with_guess['desc'].str.lower().str.contains('Katchi'.lower())
data_unlabeled_with_guess[indecies]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
1327,2022-07-26,-2.8,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
1326,2022-07-26,-2.1,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
933,2021-06-21,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
903,2021-07-08,-1.8,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
850,2021-07-30,-5.4,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
804,2021-08-23,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
1571,2022-03-22,-7.2,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
205,2020-08-12,-1.8,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
171,2020-09-07,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
159,2020-09-17,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
179,2020-09-01,-3.6,Kartenzahlung/-abrechnung SUMUP .KATCHI ICE CR...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.838434
189,2020-08-26,-1.8,Kartenzahlung/-abrechnung SUMUP .KATCHI ICE CR...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.838434

In [170]:
data_unlabeled_with_guess.loc[indecies, 'class'] = 'Restaurants & Bars'

In [ ]:
# label_dict = {
#     'Supermarket & Everyday commodities': ['Kartenzahlung/-abrechnung REWE', 'Kartenzahlung/-abrechnung EDEKA', 'Kartenzahlung/-abrechnung DIRK ROSSMANN', 'Kartenzahlung/-abrechnung DANKE, IHR LIDL', 'Kartenzahlung/-abrechnung DM', 'Kartenzahlung/-abrechnung MUELLER SAGT DANKE'],
#     'Bill - Communications': ['Lastschrift Vodafone Deutschland GmbH'],
#     'Bill - Utilities, Rent & Fees': ['Lastschrift Aberdeen Standard Investments'],
#     'Income - Salary & Benefits': ['Lohn, Gehalt, Rente IAV GmbH', 'Lohn, Gehalt, Rente Hertie School', 'Gutschrift SavingBuddies e. V. Honorar'],
#     'Income - Reimbursement': ['Gutschrift IAV GmbH'],
#     'Public Transport': ['SWAPFIETS']
# }

# for label_desc, desc_list in label_dict.items():
#     # label = {v:k for k, v in categories.items()}[label_desc]
    
#     label_index = pd.DataFrame([df_dkb['desc'].str.contains(desc) for desc in desc_list]).T.any(axis=1)
    
    
#     df_dkb.loc[label_index, 'class'] = label_desc # label

# rest

In [8]:
# dkb_data = pd.read_csv('../data/dkb.csv', index_col=0)
# dkb_data['date'] = pd.to_datetime(dkb_data['date'], format = '%Y-%m-%d')
# dkb_data

,date,amount,desc,account_nr,target account,class
0,2020-12-29,-8.00,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1,2020-12-22,-9.98,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
2,2020-12-22,-35.84,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
3,2020-12-22,-33.39,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
4,2020-12-21,-5.37,Kartenzahlung/-abrechnung REWE SAGT DANKE. 426...,1071944217,NaN,15.0
...,...,...,...,...,...,...
1684,2022-01-18,-35.70,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1685,2022-01-18,-12.99,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1686,2022-01-11,-228.09,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1687,2022-01-10,-89.96,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1688,2022-01-07,-19.50,Lastschrift SWAPFIETS BY BUCKAROO Swapfiets: D...,1071944217,NaN,13.0

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

   class_guess  class_prob
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN