# todos
1. [x] load dkd data an make ready for training
1. [x] first classifier on dkb data
2. [x] rewrite check_data and interactive script
2. [x] classify more data based on classifier and save result to disk


# infos

With this notebook, we can label the datasets, we train a model that proposes the correct class, and we either confirm or asign the correct class

In [5]:
import sys, os



import pandas as pd
import numpy as np
from pathlib import Path
# sys.path.insert(0,'..')
project_dir = str(Path(os.getcwd()).parent)
if not project_dir in sys.path:
    sys.path.insert(0,project_dir)
sys.path
from BankClassify import BankClassify

In [6]:

%load_ext autoreload

%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Label data

### load data and create classifier

In [7]:
bc = BankClassify(Path('../data'), verbose= 3, prob_threshold=0.999)

FFFFF /Users/jangie/Projects/DataScience/BankClassify/BankClassify.py
FFFFF /Users/jangie/Projects/DataScience/BankClassify/BankClassify.py
sdsdsd /Users/jangie/Projects/DataScience/BankClassify
data path: ../data
loaded previous dkb data 1689 entries
train dataset size 1267
ddd /Users/jangie/Projects/DataScience/BankClassify/notebooks/../data/categories.txt

In [209]:
data_unlabeled = bc.data_unlabeled
print(f"{len(data_unlabeled)} unlabeled entries")
predictions = bc._make_predictions(data_unlabeled)

0 unlabeled entries
ddd /Users/jangie/Projects/DataScience/BankClassify/notebooks/../data/categories.txt

In [210]:
predictions

In [199]:
# predictions.columns = ['class_guess', 'class_prob']
# predictions

### make guess

##### order by class probability

In [200]:
data_unlabeled_with_guess = pd.concat([data_unlabeled, predictions], ignore_index=False, axis=1, copy=False, join='inner')
data_unlabeled_with_guess.sort_values('class_prob', inplace=True) # sort such that the ones with the highest uncertainty come first
data_unlabeled_with_guess

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
958,2021-06-08,-6.05,Kartenzahlung/-abrechnung Steinecke s Heidebro...,1.071944e+09,NaN,NaN,Clothes & Shopping,0.188391
1220,2022-05-09,-4.30,Kartenzahlung/-abrechnung 0134000147108 H.SCH....,1.002423e+09,NaN,NaN,Presents for Others,0.331952
803,2021-08-23,-5.20,Kartenzahlung/-abrechnung 0134000147108 H.SCH....,1.071944e+09,NaN,NaN,Presents for Others,0.331952
1392,2022-06-27,-6.80,Kartenzahlung/-abrechnung M.R.. BONANZA COFFEE...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.463600
1150,2022-08-02,-7.20,Kartenzahlung/-abrechnung Lagard re Travel Ret...,1.002423e+09,NaN,NaN,Supermarket & Everyday commodities,0.534428
9,2020-12-21,-6.90,Kartenzahlung/-abrechnung Lagard re Travel Ret...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.534909
180,2020-09-01,-4.00,Kartenzahlung/-abrechnung BERLIN 10//BERLIN/DE...,1.071944e+09,NaN,NaN,Presents for Others,0.559995
960,2021-06-07,-5.50,Kartenzahlung/-abrechnung S.OL TO GO GMBH//BER...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.574325
113,2020-10-21,-4.00,Kartenzahlung/-abrechnung NYX.JNAutomation//Be...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
114,2020-10-21,-4.00,Kartenzahlung/-abrechnung NYX.JNAutomation//Be...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
616,2021-11-16,-4.50,Kartenzahlung/-abrechnung Stiftung Humboldt Fo...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
1411,2022-06-16,-6.50,Kartenzahlung/-abrechnung IZ .CAFE PINCH//BERL...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
1433,2022-06-07,-4.00,Kartenzahlung/-abrechnung Q Burger//Berlin/DE/...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
887,2021-07-13,-4.10,Kartenzahlung/-abrechnung IZ .TROPEZ NELE//BER...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
900,2021-07-08,-6.50,Kartenzahlung/-abrechnung IZ .Back Snack Bar//...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
101,2020-10-27,-4.00,Kartenzahlung/-abrechnung NYX.JNAutomation//Be...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
110,2020-10-23,-5.83,Kartenzahlung/-abrechnung Conrad Electronic St...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.608737
56,2020-11-25,-5.24,Kartenzahlung/-abrechnung PAPER-LA-PAPP//Berli...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.608737
162,2020-09-15,-5.00,Kartenzahlung/-abrechnung SANITTSHAUS MKC GMB ...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.627452
829,2021-08-10,-4.99,Kartenzahlung/-abrechnung KIK ELV61467036 06.0...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.656159
1477,2022-05-17,-5.90,Kartenzahlung/-abrechnung JONES ICE CREAM//BER...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.695074
79,2020-11-11,-6.40,Kartenzahlung/-abrechnung Imaki Restaurant GIR...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.698827
891,2021-07-13,-4.60,Kartenzahlung/-abrechnung C.A.N.S.- Cafe am Ne...,1.071944e+09,NaN,NaN,Income - Investments,0.722417
103,2020-10-26,-5.44,Kartenzahlung/-abrechnung PENNY SAGT DANKE. 37...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.736290
1484,2022-05-10,-7.50,Kartenzahlung/-abrechnung SumUp .MartinCohen//...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.826468
917,2021-06-29,-6.99,Kartenzahlung/-abrechnung 1285 ERNSTINGS FAM.B...,1.071944e+09,NaN,NaN,Clothes & Shopping,0.868739
73,2020-11-13,-6.13,Kartenzahlung/-abrechnung BAUHAUS BERLIN-CHARL...,1.071944e+09,NaN,NaN,Home Improvement & Stationary,0.980873

##### order by value

In [201]:
data_unlabeled_with_guess = pd.concat([data_unlabeled, predictions], ignore_index=False, axis=1, copy=False, join='inner')
data_unlabeled_with_guess.sort_values('amount', inplace=True, ascending=False) # sort such that the ones with the highest uncertainty come first
data_unlabeled_with_guess

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
180,2020-09-01,-4.00,Kartenzahlung/-abrechnung BERLIN 10//BERLIN/DE...,1.071944e+09,NaN,NaN,Presents for Others,0.559995
1433,2022-06-07,-4.00,Kartenzahlung/-abrechnung Q Burger//Berlin/DE/...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
101,2020-10-27,-4.00,Kartenzahlung/-abrechnung NYX.JNAutomation//Be...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
113,2020-10-21,-4.00,Kartenzahlung/-abrechnung NYX.JNAutomation//Be...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
114,2020-10-21,-4.00,Kartenzahlung/-abrechnung NYX.JNAutomation//Be...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
887,2021-07-13,-4.10,Kartenzahlung/-abrechnung IZ .TROPEZ NELE//BER...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
1220,2022-05-09,-4.30,Kartenzahlung/-abrechnung 0134000147108 H.SCH....,1.002423e+09,NaN,NaN,Presents for Others,0.331952
616,2021-11-16,-4.50,Kartenzahlung/-abrechnung Stiftung Humboldt Fo...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
891,2021-07-13,-4.60,Kartenzahlung/-abrechnung C.A.N.S.- Cafe am Ne...,1.071944e+09,NaN,NaN,Income - Investments,0.722417
829,2021-08-10,-4.99,Kartenzahlung/-abrechnung KIK ELV61467036 06.0...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.656159
162,2020-09-15,-5.00,Kartenzahlung/-abrechnung SANITTSHAUS MKC GMB ...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.627452
803,2021-08-23,-5.20,Kartenzahlung/-abrechnung 0134000147108 H.SCH....,1.071944e+09,NaN,NaN,Presents for Others,0.331952
56,2020-11-25,-5.24,Kartenzahlung/-abrechnung PAPER-LA-PAPP//Berli...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.608737
103,2020-10-26,-5.44,Kartenzahlung/-abrechnung PENNY SAGT DANKE. 37...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.736290
960,2021-06-07,-5.50,Kartenzahlung/-abrechnung S.OL TO GO GMBH//BER...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.574325
110,2020-10-23,-5.83,Kartenzahlung/-abrechnung Conrad Electronic St...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.608737
1477,2022-05-17,-5.90,Kartenzahlung/-abrechnung JONES ICE CREAM//BER...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.695074
958,2021-06-08,-6.05,Kartenzahlung/-abrechnung Steinecke s Heidebro...,1.071944e+09,NaN,NaN,Clothes & Shopping,0.188391
73,2020-11-13,-6.13,Kartenzahlung/-abrechnung BAUHAUS BERLIN-CHARL...,1.071944e+09,NaN,NaN,Home Improvement & Stationary,0.980873
79,2020-11-11,-6.40,Kartenzahlung/-abrechnung Imaki Restaurant GIR...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.698827
1411,2022-06-16,-6.50,Kartenzahlung/-abrechnung IZ .CAFE PINCH//BERL...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
900,2021-07-08,-6.50,Kartenzahlung/-abrechnung IZ .Back Snack Bar//...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.589073
1392,2022-06-27,-6.80,Kartenzahlung/-abrechnung M.R.. BONANZA COFFEE...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.463600
9,2020-12-21,-6.90,Kartenzahlung/-abrechnung Lagard re Travel Ret...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.534909
917,2021-06-29,-6.99,Kartenzahlung/-abrechnung 1285 ERNSTINGS FAM.B...,1.071944e+09,NaN,NaN,Clothes & Shopping,0.868739
1150,2022-08-02,-7.20,Kartenzahlung/-abrechnung Lagard re Travel Ret...,1.002423e+09,NaN,NaN,Supermarket & Everyday commodities,0.534428
1484,2022-05-10,-7.50,Kartenzahlung/-abrechnung SumUp .MartinCohen//...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.826468

### interactively ask if guess is correct

In [202]:
bc.prob_threshold = 1

In [203]:
df = bc._ask_with_guess(data_unlabeled_with_guess)

asking with guess, total 27
============================================================
==== to exit interactive mode enter "q" and hit enter ======
============================================================
ddd /Users/jangie/Projects/DataScience/BankClassify/notebooks/../data/categories.txt
>> tokens ['abrechnung', 'post', 'berlin', 'kartenzahlung', 'debitk.', 'deutsche']
On: 2020-09-01 00:00:00	 -4.00
Kartenzahlung/-abrechnung BERLIN 10//BERLIN/DE / DEUTSCHE POST AG 2020-08-31T15:04      Debitk.0 2024-12
My guess is: Presents for Others 56.00%

>  21

current dataset, not categorized 26/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'thuringen', 'kartenzahlung', 'burger', 'berlin', 'debitk.']
On: 2022-06-07 00:00:00	 -4.00
Kartenzahlung/-abrechnung Q Burger//Berlin/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2022-06-04T11:23      Debitk.1 2099-12
My guess is: Restaurants & Bars 58.91%

>

current dataset, not categorized 25/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'thuringen', 'kartenzahlung', 'berlin', 'debitk.', 'nyx.jnautomation']
On: 2020-10-27 00:00:00	 -4.00
Kartenzahlung/-abrechnung NYX.JNAutomation//Berlin/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2020-10-24T08:39      Debitk.1 2099-12
My guess is: Restaurants & Bars 60.86%

>  21

current dataset, not categorized 24/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'thuringen', 'kartenzahlung', 'berlin', 'debitk.', 'nyx.jnautomation']
On: 2020-10-21 00:00:00	 -4.00
Kartenzahlung/-abrechnung NYX.JNAutomation//Berlin/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2020-10-19T09:45      Debitk.1 2099-12
My guess is: Home Improvement & Stationary 60.77%

>  21

current dataset, not categorized 23/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'thuringen', 'kartenzahlung', 'berlin', 'debitk.', 'nyx.jnautomation']
On: 2020-10-21 00:00:00	 -4.00
Kartenzahlung/-abrechnung NYX.JNAutomation//Berlin/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2020-10-19T09:46      Debitk.1 2099-12
My guess is: Home Improvement & Stationary 59.79%

>  21

current dataset, not categorized 22/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'berlin', 'thuringen', 'kartenzahlung', 'nele', 'debitk.', '.tropez']
On: 2021-07-13 00:00:00	 -4.10
Kartenzahlung/-abrechnung IZ .TROPEZ NELE//BERLIN/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2021-07-11T13:19      Debitk.1 2099-12
My guess is: Restaurants & Bars 60.47%

>  17

current dataset, not categorized 21/27
>> tokens ['abrechnung', 'kartenzahlung', 'berlin', 'debitk.', 'bibl.', 'h.sch.']
On: 2022-05-09 00:00:00	 -4.30
Kartenzahlung/-abrechnung 0134000147108 H.SCH. BIBL.//Berlin/DE / 0134000147108 H.SCH. BIBL. 2022-05-03T17:52      Debitk.2 2026-12
My guess is: Presents for Others 33.32%

>  4

current dataset, not categorized 20/27
>> tokens ['abrechnung', 'landesbank', 'humboldt', 'girozentrale', 'stiftung', 'forum', 'hessen', 'thuringen', 'kartenzahlung', 'berlin', 'debitk.']
On: 2021-11-16 00:00:00	 -4.50
Kartenzahlung/-abrechnung Stiftung Humboldt Forum i//Berlin/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2021-11-14T15:08      Debitk.1 2099-12
My guess is: Restaurants & Bars 60.46%

>  18

current dataset, not categorized 19/27
>> tokens ['abrechnung', 'lichtensteinallee', 'neuen', 'gastronomieb', 'adyen', 'kartenzahlung', 'c.a.n.s.', 'berlin', 'debitk.', 'see', 'n.v.', 'cafe']
On: 2021-07-13 00:00:00	 -4.60
Kartenzahlung/-abrechnung C.A.N.S.- Cafe am Neuen See Gastronomieb/Lichtensteinallee 2/Berlin/DE / Adyen N.V. 2021-07-12T18:07      Debitk.1 2024-12
My guess is: Income - Investments 73.20%

>  16

current dataset, not categorized 18/27
>> tokens ['abrechnung', 'kik', 'sympathisch', 'kartenzahlung', 'gut', 'clever', 'elv']
On: 2021-08-10 00:00:00	 -4.99
Kartenzahlung/-abrechnung KIK ELV61467036 06.08 13.04 ME1 KIK-SYMPATHISCH CLEVER GUT
My guess is: Supermarket & Everyday commodities 65.60%

>  24

current dataset, not categorized 17/27
>> tokens ['abrechnung', 'berlin', 'gmb', 'kartenzahlung', 'sanittshaus', 'mkc', 'debitk.']
On: 2020-09-15 00:00:00	 -5.00
Kartenzahlung/-abrechnung SANITTSHAUS MKC GMB BERLIN//BERLIN/DE / SANITTSHAUS MKC GMB BERLIN 2020-09-14T16:09      Debitk.0 2024-12
My guess is: Supermarket & Everyday commodities 62.65%

>  7

current dataset, not categorized 16/27
>> tokens ['abrechnung', 'kartenzahlung', 'berlin', 'debitk.', 'bibl.', 'h.sch.']
On: 2021-08-23 00:00:00	 -5.20
Kartenzahlung/-abrechnung 0134000147108 H.SCH. BIBL.//Berlin/DE / 0134000147108 H.SCH. BIBL. 2021-08-17T17:42      Debitk.0 2024-12
My guess is: Presents for Others 33.61%

>  4

current dataset, not categorized 15/27
>> tokens ['abrechnung', 'papp', 'paper', 'kartenzahlung', 'berlin', 'debitk.']
On: 2020-11-25 00:00:00	 -5.24
Kartenzahlung/-abrechnung PAPER-LA-PAPP//Berlin/DE / PAPER-LA-PAPP 2020-11-24T14:27      Debitk.1 2024-12
My guess is: Supermarket & Everyday commodities 60.19%

>  23

current dataset, not categorized 14/27
>> tokens ['abrechnung', 'penny', 'charlottenb', 'sagt', 'danke.', 'kartenzahlung', 'berlin', 'leibnizstras', 'debitk.']
On: 2020-10-26 00:00:00	 -5.44
Kartenzahlung/-abrechnung PENNY SAGT DANKE. 37302357//Berlin Charlottenb/DE / Penny Leibnizstras 2020-10-24T10:34      Debitk.0 2024-12
My guess is: Supermarket & Everyday commodities 73.72%

>

current dataset, not categorized 13/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'berlin', 'thuringen', 'gmbh', 'kartenzahlung', 'debitk.', 's.ol']
On: 2021-06-07 00:00:00	 -5.50
Kartenzahlung/-abrechnung S.OL TO GO GMBH//BERLIN/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2021-06-03T10:59      Debitk.1 2099-12
My guess is: Restaurants & Bars 60.38%

>  15

current dataset, not categorized 12/27
>> tokens ['abrechnung', 'conrad', 'stores', 'electronic', 'kartenzahlung', 'berlin', 'debitk.']
On: 2020-10-23 00:00:00	 -5.83
Kartenzahlung/-abrechnung Conrad Electronic Stores157135//Berlin/DE / CONRAD 153561 2020-10-22T18:30      Debitk.0 2024-12
My guess is: Supermarket & Everyday commodities 60.24%

>  21

current dataset, not categorized 11/27
>> tokens ['abrechnung', 'landesbank', 'cream', 'girozentrale', 'hessen', 'jones', 'berlin', 'thuringen', 'ice', 'kartenzahlung', 'debitk.']
On: 2022-05-17 00:00:00	 -5.90
Kartenzahlung/-abrechnung JONES ICE CREAM//BERLIN/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2022-05-14T14:52      Debitk.1 2099-12
My guess is: Restaurants & Bars 70.32%

>

current dataset, not categorized 10/27
>> tokens ['abrechnung', 'steinecke', 'kartenzahlung', 'heidebrot', 'elv']
On: 2021-06-08 00:00:00	 -6.05
Kartenzahlung/-abrechnung Steinecke s Heidebrot ELV54158014 04.06 09.02 ME1
My guess is: Clothes & Shopping 20.29%

>  15

current dataset, not categorized 9/27
>> tokens ['abrechnung', 'bauhaus', 'berlin', 'kartenzahlung', 'charlottenbg', 'elv']
On: 2020-11-13 00:00:00	 -6.13
Kartenzahlung/-abrechnung BAUHAUS BERLIN-CHARLOTTENBG 111114051051824241201081210 ELV65130699 11.11 14.05 ME1
My guess is: Home Improvement & Stationary 97.97%

>

current dataset, not categorized 8/27
>> tokens ['gir', 'abrechnung', 'imaki', 'berlin', 'kartenzahlung', 'debitk.', 'restaurant']
On: 2020-11-11 00:00:00	 -6.40
Kartenzahlung/-abrechnung Imaki Restaurant GIR 69302918//BERLIN/DE / Imaki Restaurant 2020-11-10T12:08      Debitk.0 2024-12
My guess is: Restaurants & Bars 70.17%

>

current dataset, not categorized 7/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', 'hessen', 'berlin', 'thuringen', 'kartenzahlung', 'debitk.', '.cafe', 'pinch']
On: 2022-06-16 00:00:00	 -6.50
Kartenzahlung/-abrechnung IZ .CAFE PINCH//BERLIN/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2022-06-14T12:23      Debitk.1 2099-12
My guess is: Restaurants & Bars 65.28%

>

current dataset, not categorized 6/27
>> tokens ['snack', 'abrechnung', 'landesbank', 'girozentrale', 'bar', 'hessen', 'berlin', 'thuringen', 'kartenzahlung', 'debitk.', '.back']
On: 2021-07-08 00:00:00	 -6.50
Kartenzahlung/-abrechnung IZ .Back Snack Bar//BERLIN/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2021-07-06T10:22      Debitk.0 2099-12
My guess is: Restaurants & Bars 67.00%

>

current dataset, not categorized 5/27
>> tokens ['abrechnung', 'bonanza', 'landesbank', 'girozentrale', 'hessen', 'berlin', 'coffee', 'thuringen', 'kartenzahlung', 'debitk.', 'm.r..']
On: 2022-06-27 00:00:00	 -6.80
Kartenzahlung/-abrechnung M.R.. BONANZA COFFEE//BERLIN/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2022-06-23T07:51      Debitk.1 2099-12
My guess is: Restaurants & Bars 56.54%

>

current dataset, not categorized 4/27
>> tokens ['lagard', 'abrechnung', 'travel', 'retail', 'kartenzahlung', 'berlin', 'debitk.', 'gmbh']
On: 2020-12-21 00:00:00	 -6.90
Kartenzahlung/-abrechnung Lagard re Travel Retail//Berlin/DE / Lagard re Travel Retail DE GmbH 2020-12-20T09:51      Debitk.1 2024-12
My guess is: Supermarket & Everyday commodities 53.57%

>  16

current dataset, not categorized 3/27
>> tokens ['abrechnung', 'fam.berlin', 'ernstings', 'kartenzahlung', 'elv']
On: 2021-06-29 00:00:00	 -6.99
Kartenzahlung/-abrechnung 1285 ERNSTINGS FAM.BERLIN 260612111062327241200012850 ELV65200371 26.06 12.11 ME1
My guess is: Clothes & Shopping 87.71%

>

current dataset, not categorized 2/27
>> tokens ['lagard', 'abrechnung', 'travel', 'hbf', 'retail', 'kartenzahlung', 'berlin', 'relay', 'gmbh']
On: 2022-08-02 00:00:00	 -7.20
Kartenzahlung/-abrechnung Lagard re Travel Retail//Berlin/DE / Lagard re Travel Retail DE GmbH RELAY Berlin HBF 722-2
My guess is: Presents for Others 38.01%

>  16

current dataset, not categorized 1/27
>> tokens ['abrechnung', 'landesbank', 'girozentrale', '.martincohen', 'hessen', 'thuringen', 'kartenzahlung', 'berlin', 'debitk.', 'sumup']
On: 2022-05-10 00:00:00	 -7.50
Kartenzahlung/-abrechnung SumUp .MartinCohen//Berlin/DE/0 / Landesbank Hessen-Thuringen Girozentrale 2022-05-07T14:03      Debitk.1 2099-12
My guess is: Restaurants & Bars 88.09%

>

current dataset, not categorized 0/27

In [27]:
16# data_unlabeled_with_guess

In [10]:
len(data_unlabeled_with_guess)

295

In [11]:
data_unlabeled_with_guess

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
1201,2022-06-02,-2070.00,"Überweisung DANNY KRAUTZ Buzios, praja, sol, f...",1.002423e+09,NaN,Income - Reimbursement,Bill - Health,0.887936
531,2020-05-29,-700.00,Überweisung ERICO VICENTE CIANCIO armario ...,1.002423e+09,NaN,Home Improvement & Stationary,Bill - Health,0.926238
592,2021-11-29,-595.00,"Überweisung DOMUS AG Rechnr.945, Mandant: 4082...",1.071944e+09,NaN,"Bill - Utilities, Rent & Fees",Bill - Health,0.887936
364,2021-04-06,-530.14,Überweisung NOAK KUBE TISCHLEREI GMBH Schreibt...,1.002423e+09,NaN,Home Improvement & Stationary,Bill - Health,0.948915
1315,2022-08-02,-300.00,Kartenzahlung/-abrechnung Hotel Kranichsberg//...,1.071944e+09,NaN,Holidays - Accomodation,Clothes & Shopping,0.913434
...,...,...,...,...,...,...,...,...
537,2020-05-05,3000.00,Gutschrift CORNELIA GIESELER UND DR. S TEFFEN ...,1.002423e+09,NaN,NaN,Income - Presents,0.993445
559,2020-01-03,4000.00,Gutschrift DR.ST. U. C. GIESELER Weihnachten O...,1.002423e+09,NaN,NaN,Income - Presents,0.996949
334,2021-05-26,4111.75,Gutschrift DR.ST. U. C. GIESELER Betrag Aktien...,1.002423e+09,NaN,NaN,Income - Presents,0.999664
532,2020-05-25,5000.00,Gutschrift DR.ST. U. C. GIESELER Koblenz Oma.O...,1.002423e+09,NaN,NaN,Income - Presents,0.994370
1353,2022-07-15,80000.00,Gutschrift KTO3036000010004294/ JOAO VIRGILIO ...,1.071944e+09,NaN,NaN,Income - Presents,0.998048

In [12]:
len(bc.data['dkb'])

1689

In [13]:
# data_unlabeled_with_guess.loc[311]

In [ ]:
bc.data['dkb'].loc[311]

<a id=’section_update’></a>
### update the dataset

In [204]:
bc.update_data(data_unlabeled_with_guess)

In [205]:
# bc.data['dkb'].update(data_unlabeled_with_guess[data_unlabeled_with_guess.columns[~data_unlabeled_with_guess.columns.isin(['class_guess', 'class_prob'])]])

#### save dataset

In [206]:
bc.save_data()

### manual labeling

after asigning the labels or the target account go to [Section Update](#section_update) to update and save the data to disk.

##### add target account

In [23]:
data_unlabeled_with_guess[data_unlabeled_with_guess['target account'].isna()]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
1602,2022-03-08,-25.30,Kartenzahlung/-abrechnung CAFE IM LITERATURHAU...,1.071944e+09,NaN,NaN,Home Improvement & Stationary,0.311130
656,2021-11-01,-17.00,Kartenzahlung/-abrechnung DORINT GMBH GIR 6929...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.372674
652,2021-11-01,-123.80,Kartenzahlung/-abrechnung DORINT GMBH GIR 6929...,1.071944e+09,NaN,NaN,Restaurants & Bars,0.372674
749,2021-09-13,-10.68,Kartenzahlung/-abrechnung DANKE FLEISCHEREI GL...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.471710
682,2021-10-18,-25.72,Kartenzahlung/-abrechnung DANKE FLEISCHEREI GL...,1.071944e+09,NaN,NaN,Supermarket & Everyday commodities,0.471710
...,...,...,...,...,...,...,...,...
1206,2022-05-30,500.00,Gutschrift DR.ST. U. C. GIESELER Alles Gute zu...,1.002423e+09,NaN,NaN,Income - Presents,0.999417
334,2021-05-26,4111.75,Gutschrift DR.ST. U. C. GIESELER Betrag Aktien...,1.002423e+09,NaN,NaN,Income - Presents,0.999656
520,2020-07-01,-2229.12,Lastschrift Aberdeen Asset Management Deutschl...,1.002423e+09,NaN,NaN,"Bill - Utilities, Rent & Fees",0.999687
1171,2022-07-04,-120.00,Überweisung EDITH ESPINOZA DE THIEKE Rechn.Nr....,1.002423e+09,NaN,NaN,"Bill - Utilities, Rent & Fees",0.999821
410,2021-02-02,12.50,Gutschrift DR.ST. U. C. GIESELER Dividende aus...,1.002423e+09,NaN,NaN,Income - Presents,0.999851

In [56]:
bc.data['dkb']['target account'].unique()

array(['paypal', nan, 'Sabadell', 'dkb', 'credit card'], dtype=object)

In [143]:
# data_unlabeled_with_guess

In [55]:
credit_indecies = data_unlabeled_with_guess['desc'].str.lower().str.contains('Gutschrift Jan Gieseler'.lower())
credit_indecies.sum()
data_unlabeled_with_guess[credit_indecies]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
554,2020-02-04,1000.00,Gutschrift JAN GIESELER poupar ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
551,2020-02-19,2500.00,Gutschrift JAN GIESELER poupen ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
547,2020-03-26,2500.00,Gutschrift JAN GIESELER popen ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
341,2021-05-11,12548.11,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
467,2020-10-28,2750.00,Gutschrift JAN GIESELER restbetrag ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
516,2020-07-14,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
437,2020-12-08,2750.00,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
512,2020-07-27,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
539,2020-04-24,2500.00,Gutschrift JAN GIESELER spargeld ...,1.002423e+09,NaN,NaN,Public Transport,0.885461
522,2020-06-26,2500.00,Gutschrift JAN GIESELER poupa ...,1.002423e+09,NaN,NaN,Public Transport,0.885461

In [57]:
data_unlabeled_with_guess.loc[credit_indecies, 'target account'] = 'Sabadell'

In [58]:
data_unlabeled_with_guess[credit_indecies]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
554,2020-02-04,1000.00,Gutschrift JAN GIESELER poupar ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
551,2020-02-19,2500.00,Gutschrift JAN GIESELER poupen ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
547,2020-03-26,2500.00,Gutschrift JAN GIESELER popen ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
341,2021-05-11,12548.11,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
467,2020-10-28,2750.00,Gutschrift JAN GIESELER restbetrag ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
516,2020-07-14,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
437,2020-12-08,2750.00,Gutschrift JAN GIESELER kontoaufloesung ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
512,2020-07-27,2500.00,Gutschrift JAN GIESELER reserve ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
539,2020-04-24,2500.00,Gutschrift JAN GIESELER spargeld ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461
522,2020-06-26,2500.00,Gutschrift JAN GIESELER poupa ...,1.002423e+09,Sabadell,NaN,Public Transport,0.885461

In [46]:
credit_indecies.sum()

7

##### set labels

In [169]:
indecies = data_unlabeled_with_guess['desc'].str.lower().str.contains('Katchi'.lower())
data_unlabeled_with_guess[indecies]

,date,amount,desc,account_nr,target account,class,class_guess,class_prob
1327,2022-07-26,-2.8,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
1326,2022-07-26,-2.1,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
933,2021-06-21,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
903,2021-07-08,-1.8,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
850,2021-07-30,-5.4,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
804,2021-08-23,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
1571,2022-03-22,-7.2,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
205,2020-08-12,-1.8,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
171,2020-09-07,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
159,2020-09-17,-3.6,Kartenzahlung/-abrechnung SumUp .Katchi Ice Cr...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.541483
179,2020-09-01,-3.6,Kartenzahlung/-abrechnung SUMUP .KATCHI ICE CR...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.838434
189,2020-08-26,-1.8,Kartenzahlung/-abrechnung SUMUP .KATCHI ICE CR...,1.071944e+09,NaN,NaN,Holidays - Accomodation,0.838434

In [170]:
data_unlabeled_with_guess.loc[indecies, 'class'] = 'Restaurants & Bars'

In [ ]:
# label_dict = {
#     'Supermarket & Everyday commodities': ['Kartenzahlung/-abrechnung REWE', 'Kartenzahlung/-abrechnung EDEKA', 'Kartenzahlung/-abrechnung DIRK ROSSMANN', 'Kartenzahlung/-abrechnung DANKE, IHR LIDL', 'Kartenzahlung/-abrechnung DM', 'Kartenzahlung/-abrechnung MUELLER SAGT DANKE'],
#     'Bill - Communications': ['Lastschrift Vodafone Deutschland GmbH'],
#     'Bill - Utilities, Rent & Fees': ['Lastschrift Aberdeen Standard Investments'],
#     'Income - Salary & Benefits': ['Lohn, Gehalt, Rente IAV GmbH', 'Lohn, Gehalt, Rente Hertie School', 'Gutschrift SavingBuddies e. V. Honorar'],
#     'Income - Reimbursement': ['Gutschrift IAV GmbH'],
#     'Public Transport': ['SWAPFIETS']
# }

# for label_desc, desc_list in label_dict.items():
#     # label = {v:k for k, v in categories.items()}[label_desc]
    
#     label_index = pd.DataFrame([df_dkb['desc'].str.contains(desc) for desc in desc_list]).T.any(axis=1)
    
    
#     df_dkb.loc[label_index, 'class'] = label_desc # label

# rest

In [8]:
# dkb_data = pd.read_csv('../data/dkb.csv', index_col=0)
# dkb_data['date'] = pd.to_datetime(dkb_data['date'], format = '%Y-%m-%d')
# dkb_data

,date,amount,desc,account_nr,target account,class
0,2020-12-29,-8.00,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1,2020-12-22,-9.98,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
2,2020-12-22,-35.84,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
3,2020-12-22,-33.39,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
4,2020-12-21,-5.37,Kartenzahlung/-abrechnung REWE SAGT DANKE. 426...,1071944217,NaN,15.0
...,...,...,...,...,...,...
1684,2022-01-18,-35.70,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1685,2022-01-18,-12.99,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1686,2022-01-11,-228.09,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1687,2022-01-10,-89.96,"Lastschrift PAYPAL (EUROPE) S.A.R.L ET CIE,S.C...",1071944217,paypal,NaN
1688,2022-01-07,-19.50,Lastschrift SWAPFIETS BY BUCKAROO Swapfiets: D...,1071944217,NaN,13.0

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

   class_guess  class_prob
0          NaN         NaN
1          NaN         NaN
2          NaN         NaN
3          NaN         NaN
4          NaN         NaN